; db "BULBASAUR @"
	; db "IVYSAUR   @"
	; db "VENUSAUR  @"
	; db "CHARMANDER@"
	; db "CHARMELEON@"
	; db "CHARIZARD @"
	; db "SQUIRTLE  @"
	; db "WARTORTLE @"
	; db "BLASTOISE @"
	; db "CATERPIE  @"
	; db "METAPOD   @"
	; db "BUTTERFREE@"
	; db "WEEDLE    @"
	; db "KAKUNA    @"
	; db "BEEDRILL  @"
	; db "PIDGEY    @"
	; db "PIDGEOTTO @"
	; db "PIDGEOT   @"
	; db "RATTATA   @"
	; db "RATICATE  @"
	; db "SPEAROW   @"
	; db "FEAROW    @"
	; db "EKANS     @"
	; db "ARBOK     @"
	; db "PIKACHU   @"
	; db "RAICHU    @"
	; db "SANDSHREW @"
	; db "SANDSLASH @"
	; db "NIDORAN♂  @"
	; db "NIDORINA  @"
	; db "NIDOQUEEN @"
	; db "NIDORAN♀  @"
	; db "NIDORINO  @"
	; db "NIDOKING  @"
	; db "CLEFAIRY  @"
	; db "CLEFABLE  @"
	; db "VULPIX    @"
	; db "NINETALES @"
	; db "JIGGLYPUFF@"
	; db "WIGGLYTUFF@"
	; db "ZUBAT     @"
	; db "GOLBAT    @"
	; db "ODDISH    @"
	; db "GLOOM     @"
	; db "VILEPLUME @"
	; db "PARAS     @"
	; db "PARASECT  @"
	; db "VENONAT   @"
	; db "VENOMOTH  @"
	; db "DIGLETT   @"
	; db "DUGTRIO   @"
	; db "MEOWTH    @"
	; db "PERSIAN   @"
	; db "PSYDUCK   @"
	; db "GOLDUCK   @"
	; db "MANKEY    @"
	; db "PRIMEAPE  @"
	; db "GROWLITHE @"
	; db "ARCANINE  @"
	; db "POLIWAG   @"
	; db "POLIWHIRL @"
	; db "POLIWRATH @"
	; db "ABRA      @"
	; db "KADABRA   @"
	; db "ALAKAZAM  @"
	; db "MACHOP    @"
	; db "MACHOKE   @"
	; db "MACHAMP   @"
	; db "BELLSPROUT@"
	; db "WEEPINBELL@"
	; db "VICTREEBEL@"
	; db "TENTACOOL @"
	; db "TENTACRUEL@"
	; db "GEODUDE   @"
	; db "GRAVELER  @"
	; db "GOLEM     @"
	; db "PONYTA    @"
	; db "RAPIDASH  @"
	; db "SLOWPOKE  @"
	; db "SLOWBRO   @"
	; db "MAGNEMITE @"
	; db "MAGNETON  @"
	; db "FARFETCH`D@"
	; db "DODUO     @"
	; db "DODRIO    @"
	; db "SEEL      @"
	; db "DEWGONG   @"
	; db "GRIMER    @"
	; db "MUK       @"
	; db "SHELLDER  @"
	; db "CLOYSTER  @"
	; db "GASTLY    @"
	; db "HAUNTER   @"
	; db "GENGAR    @"
	; db "ONIX      @"
	; db "DROWZEE   @"
	; db "HYPNO     @"
	; db "KRABBY    @"
	; db "KINGLER   @"
	; db "VOLTORB   @"
	; db "ELECTRODE @"
	; db "EXEGGCUTE @"
	; db "EXEGGUTOR @"
	; db "CUBONE    @"
	; db "MAROWAK   @"
	; db "HITMONLEE @"
	; db "HITMONCHAN@"
	; db "LICKITUNG @"
	; db "KOFFING   @"
	; db "WEEZING   @"
	; db "RHYHORN   @"
	; db "RHYDON    @"
	; db "CHANSEY   @"
	; db "TANGELA   @"
	; db "KANGASKHAN@"
	; db "HORSEA    @"
	; db "SEADRA    @"
	; db "GOLDEEN   @"
	; db "SEAKING   @"
	; db "STARYU    @"
	; db "STARMIE   @"
	; db "MR.MIME   @"
	; db "SCYTHER   @"
	; db "JYNX      @"
	; db "ELECTABUZZ@"
	; db "MAGMAR    @"
	; db "PINSIR    @"
	; db "TAUROS    @"
	; db "MAGIKARP  @"
	; db "GYARADOS  @"
	; db "LAPRAS    @"
	; db "DITTO     @"
	; db "EEVEE     @"
	; db "VAPOREON  @"
	; db "JOLTEON   @"
	; db "FLAREON   @"
	; db "PORYGON   @"
	; db "OMANYTE   @"
	; db "OMASTAR   @"
	; db "KABUTO    @"
	; db "KABUTOPS  @"
	; db "AERODACTYL@"
	; db "SNORLAX   @"
	; db "ARTICUNO  @"
	; db "ZAPDOS    @"
	; db "MOLTRES   @"
	; db "DRATINI   @"
	; db "DRAGONAIR @"
	; db "DRAGONITE @"
	; db "MEWTWO    @"
	; db "MEW       @"
MonDexNames: ; 0x29892
IF DEF(_CHS)
	db_w "妙蛙种子@@@"
	db_w "妙蛙草@@@@@"
	db_w "妙蛙花@@@@@"
	db_w "小火龙@@@@@"
	db_w "火恐龙@@@@@"
	db_w "喷火龙@@@@@"
	db_w "杰尼龟@@@@@"
	db_w "卡咪龟@@@@@"
	db_w "水箭龟@@@@@"
	db_w "绿毛虫@@@@@"
	db_w "铁甲蛹@@@@@"
	db_w "巴大蝶@@@@@"
	db_w "独角虫@@@@@"
	db_w "铁壳蛹@@@@@"
	db_w "大针蜂@@@@@"
	db_w "波波@@@@@@@"
	db_w "比比鸟@@@@@"
	db_w "大比鸟@@@@@"
	db_w "小拉达@@@@@"
	db_w "拉达@@@@@@@"
	db_w "烈雀@@@@@@@"
	db_w "大嘴雀@@@@@"
	db_w "阿柏蛇@@@@@"
	db_w "阿柏怪@@@@@"
	db_w "皮卡丘@@@@@"
	db_w "雷丘@@@@@@@"
	db_w "穿山鼠@@@@@"
	db_w "穿山王@@@@@"
	db_w "尼多兰@@@@@"
	db_w "尼多娜@@@@@"
	db_w "尼多后@@@@@"
	db_w "尼多朗@@@@@"
	db_w "尼多力诺@@@"
	db_w "尼多王@@@@@"
	db_w "皮皮@@@@@@@"
	db_w "皮可西@@@@@"
	db_w "六尾@@@@@@@"
	db_w "九尾@@@@@@@"
	db_w "胖丁@@@@@@@"
	db_w "胖可丁@@@@@"
	db_w "超音蝠@@@@@"
	db_w "大嘴蝠@@@@@"
	db_w "走路草@@@@@"
	db_w "臭臭花@@@@@"
	db_w "霸王花@@@@@"
	db_w "派拉斯@@@@@"
	db_w "派拉斯特@@@"
	db_w "毛球@@@@@@@"
	db_w "摩鲁蛾@@@@@"
	db_w "地鼠@@@@@@@"
	db_w "三地鼠@@@@@"
	db_w "喵喵@@@@@@@"
	db_w "猫老大@@@@@"
	db_w "可达鸭@@@@@"
	db_w "哥达鸭@@@@@"
	db_w "猴怪@@@@@@@"
	db_w "火暴猴@@@@@"
	db_w "卡蒂狗@@@@@"
	db_w "风速狗@@@@@"
	db_w "蚊香蝌蚪@@@"
	db_w "蚊香君@@@@@"
	db_w "蚊香泳士@@@"
	db_w "凯西@@@@@@@"
	db_w "勇基拉@@@@@"
	db_w "胡地@@@@@@@"
	db_w "腕力@@@@@@@"
	db_w "豪力@@@@@@@"
	db_w "怪力@@@@@@@"
	db_w "喇叭芽@@@@@"
	db_w "口呆花@@@@@"
	db_w "大食花@@@@@"
	db_w "玛瑙水母@@@"
	db_w "毒刺水母@@@"
	db_w "小拳石@@@@@"
	db_w "隆隆石@@@@@"
	db_w "隆隆岩@@@@@"
	db_w "小火马@@@@@"
	db_w "烈焰马@@@@@"
	db_w "呆呆兽@@@@@"
	db_w "呆壳兽@@@@@"
	db_w "小磁怪@@@@@"
	db_w "三合一磁怪@"
	db_w "大葱鸭@@@@@"
	db_w "嘟嘟@@@@@@@"
	db_w "嘟嘟利@@@@@"
	db_w "小海狮@@@@@"
	db_w "白海狮@@@@@"
	db_w "臭泥@@@@@@@"
	db_w "臭臭泥@@@@@"
	db_w "大舌贝@@@@@"
	db_w "刺甲贝@@@@@"
	db_w "鬼斯@@@@@@@"
	db_w "鬼斯通@@@@@"
	db_w "耿鬼@@@@@@@"
	db_w "大岩蛇@@@@@"
	db_w "催眠貘@@@@@"
	db_w "引梦貘人@@@"
	db_w "大钳蟹@@@@@"
	db_w "巨钳蟹@@@@@"
	db_w "霹雳电球@@@"
	db_w "顽皮雷弹@@@"
	db_w "蛋蛋@@@@@@@"
	db_w "椰蛋树@@@@@"
	db_w "卡拉卡拉@@@"
	db_w "嘎啦嘎啦@@@"
	db_w "飞腿郎@@@@@"
	db_w "快拳郎@@@@@"
	db_w "大舌头@@@@@"
	db_w "瓦斯弹@@@@@"
	db_w "双弹瓦斯@@@"
	db_w "独角犀牛@@@"
	db_w "钻角犀兽@@@"
	db_w "吉利蛋@@@@@"
	db_w "蔓藤怪@@@@@"
	db_w "袋兽@@@@@@@"
	db_w "墨海马@@@@@"
	db_w "海刺龙@@@@@"
	db_w "角金鱼@@@@@"
	db_w "金鱼王@@@@@"
	db_w "海星星@@@@@"
	db_w "宝石海星@@@"
	db_w "魔墙人偶@@@"
	db_w "飞天螳螂@@@"
	db_w "迷唇姐@@@@@"
	db_w "电击兽@@@@@"
	db_w "鸭嘴火兽@@@"
	db_w "凯罗斯@@@@@"
	db_w "肯泰罗@@@@@"
	db_w "鲤鱼王@@@@@"
	db_w "暴鲤龙@@@@@"
	db_w "拉普拉斯@@@"
	db_w "百变怪@@@@@"
	db_w "伊布@@@@@@@"
	db_w "水伊布@@@@@"
	db_w "雷伊布@@@@@"
	db_w "火伊布@@@@@"
	db_w "多边兽@@@@@"
	db_w "菊石兽@@@@@"
	db_w "多刺菊石兽@"
	db_w "化石盔@@@@@"
	db_w "镰刀盔@@@@@"
	db_w "化石翼龙@@@"
	db_w "卡比兽@@@@@"
	db_w "急冻鸟@@@@@"
	db_w "闪电鸟@@@@@"
	db_w "火焰鸟@@@@@"
	db_w "迷你龙@@@@@"
	db_w "哈克龙@@@@@"
	db_w "快龙@@@@@@@"
	db_w "超梦@@@@@@@"
	db_w "梦幻@@@@@@@"
ELSE
	db_w "이상해씨@@@"
	db_w "이상해풀@@@"
	db_w "이상해꽃@@@"
	db_w "파이리@@@@@"
	db_w "리자드@@@@@"
	db_w "리자몽@@@@@"
	db_w "꼬부기@@@@@"
	db_w "어니부기@@@"
	db_w "거북왕@@@@@"
	db_w "캐터피@@@@@"
	db_w "단데기@@@@@"
	db_w "버터플@@@@@"
	db_w "뿔충이@@@@@"
	db_w "딱충이@@@@@"
	db_w "독침붕@@@@@"
	db_w "구구@@@@@@@"
	db_w "피죤@@@@@@@"
	db_w "피죤투@@@@@"
	db_w "꼬렛@@@@@@@"
	db_w "레트라@@@@@"
	db_w "깨비참@@@@@"
	db_w "깨비드릴조@"
	db_w "아보@@@@@@@"
	db_w "아보크@@@@@"
	db_w "피카츄@@@@@"
	db_w "라이츄@@@@@"
	db_w "모래두지@@@"
	db_w "고지@@@@@@@"
	db_w "니드런<♀>@@@"
	db_w "니드리나@@@"
	db_w "니드퀸@@@@@"
	db_w "니드런<♂>@@@"
	db_w "니드리노@@@"
	db_w "니드킹@@@@@"
	db_w "삐삐@@@@@@@"
	db_w "픽시@@@@@@@"
	db_w "식스테일@@@"
	db_w "나인테일@@@"
	db_w "푸린@@@@@@@"
	db_w "푸크린@@@@@"
	db_w "주뱃@@@@@@@"
	db_w "골뱃@@@@@@@"
	db_w "뚜벅쵸@@@@@"
	db_w "냄새꼬@@@@@"
	db_w "라플레시아@"
	db_w "파라스@@@@@"
	db_w "파라섹트@@@"
	db_w "콘팡@@@@@@@"
	db_w "도나리@@@@@"
	db_w "디그다@@@@@"
	db_w "닥트리오@@@"
	db_w "나옹@@@@@@@"
	db_w "페르시온@@@"
	db_w "고라파덕@@@"
	db_w "골덕@@@@@@@"
	db_w "망키@@@@@@@"
	db_w "성원숭@@@@@"
	db_w "가디@@@@@@@"
	db_w "윈디@@@@@@@"
	db_w "발챙이@@@@@"
	db_w "수륙챙이@@@"
	db_w "강챙이@@@@@"
	db_w "캐이시@@@@@"
	db_w "윤겔라@@@@@"
	db_w "후딘@@@@@@@"
	db_w "알통몬@@@@@"
	db_w "근육몬@@@@@"
	db_w "괴력몬@@@@@"
	db_w "모다피@@@@@"
	db_w "우츠동@@@@@"
	db_w "우츠보트@@@"
	db_w "왕눈해@@@@@"
	db_w "독파리@@@@@"
	db_w "꼬마돌@@@@@"
	db_w "데구리@@@@@"
	db_w "딱구리@@@@@"
	db_w "포니타@@@@@"
	db_w "날쌩마@@@@@"
	db_w "야돈@@@@@@@"
	db_w "야도란@@@@@"
	db_w "코일@@@@@@@"
	db_w "레어코일@@@"
	db_w "파오리@@@@@"
	db_w "두두@@@@@@@"
	db_w "두트리오@@@"
	db_w "쥬쥬@@@@@@@"
	db_w "쥬레곤@@@@@"
	db_w "질퍽이@@@@@"
	db_w "질뻐기@@@@@"
	db_w "셀러@@@@@@@"
	db_w "파르셀@@@@@"
	db_w "고오스@@@@@"
	db_w "고우스트@@@"
	db_w "팬텀@@@@@@@"
	db_w "롱스톤@@@@@"
	db_w "슬리프@@@@@"
	db_w "슬리퍼@@@@@"
	db_w "크랩@@@@@@@"
	db_w "킹크랩@@@@@"
	db_w "찌리리공@@@"
	db_w "붐볼@@@@@@@"
	db_w "아라리@@@@@"
	db_w "나시@@@@@@@"
	db_w "탕구리@@@@@"
	db_w "텅구리@@@@@"
	db_w "시라소몬@@@"
	db_w "홍수몬@@@@@"
	db_w "내루미@@@@@"
	db_w "또가스@@@@@"
	db_w "또도가스@@@"
	db_w "뿔카노@@@@@"
	db_w "코뿌리@@@@@"
	db_w "럭키@@@@@@@"
	db_w "덩구리@@@@@"
	db_w "캥카@@@@@@@"
	db_w "쏘드라@@@@@"
	db_w "시드라@@@@@"
	db_w "콘치@@@@@@@"
	db_w "왕콘치@@@@@"
	db_w "별가사리@@@"
	db_w "아쿠스타@@@"
	db_w "마임맨@@@@@"
	db_w "스라크@@@@@"
	db_w "루주라@@@@@"
	db_w "에레브@@@@@"
	db_w "마그마@@@@@"
	db_w "쁘사이저@@@"
	db_w "켄타로스@@@"
	db_w "잉어킹@@@@@"
	db_w "갸라도스@@@"
	db_w "라프라스@@@"
	db_w "메타몽@@@@@"
	db_w "이브이@@@@@"
	db_w "샤미드@@@@@"
	db_w "쥬피썬더@@@"
	db_w "부스터@@@@@"
	db_w "폴리곤@@@@@"
	db_w "암나이트@@@"
	db_w "암스타@@@@@"
	db_w "투구@@@@@@@"
	db_w "투구푸스@@@"
	db_w "프테라@@@@@"
	db_w "잠만보@@@@@"
	db_w "프리져@@@@@"
	db_w "썬더@@@@@@@"
	db_w "파이어@@@@@"
	db_w "미뇽@@@@@@@"
	db_w "신뇽@@@@@@@"
	db_w "망나뇽@@@@@"
	db_w "뮤츠@@@@@@@"
	db_w "뮤@@@@@@@@"
ENDC